const { model, Schema } = require("mongoose");

const Recipe = new Schema({
    meal: String,
    id: Number,
    image: String,
    instructions: String,
    ingredients: {
        one: String,
        two: String,
        three: String,
        four: String,
        five: String,
        six: String,
        seven: String,
        eight: String,
        nine: String,
        ten: String,
        eleven: String,
        tweleve: String,
        thirteen: String,
        fourteen: String,
        fifteen: String,
        sixteen: String,
        seventeen: String,
        eighteen: String,
        nineteen: String,
        twenty: String,
    },
    measurements: {
        one: String,
        two: String,
        three: String,
        four: String,
        five: String,
        six: String,
        seven: String,
        eight: String,
        nine: String,
        ten: String,
        eleven: String,
        tweleve: String,
        thirteen: String,
        fourteen: String,
        fifteen: String,
        sixteen: String,
        seventeen: String,
        eighteen: String,
        nineteen: String,
        twenty: String,
    },
    tutorial: String,
    toTry: {
        type: Boolean,
        default: false,
    },
    made: {
        type: Boolean,
        default: false,
    },
    favorite: {
        type: Boolean,
        default: false,
    },
});

module.exports = model('recipe', Recipe);